CREATE TABLE User
(
	user_ID 	BIGINT UNSIGNED 		NOT NULL AUTO_INCREMENT,
	username 	VARCHAR(255)			UNIQUE,
	uploads		BIGINT UNSIGNED,
	user_since	DATETIME,

	PRIMARY KEY (user_ID)

);

CREATE TABLE Media
(
	media_ID		BIGINT UNSIGNED 	NOT NULL AUTO_INCREMENT,
	filename		VARCHAR(18)			UNIQUE,
	upload_date 	DATETIME			DEFAULT NOW(),
	uploader 		BIGINT UNSIGNED,

	PRIMARY KEY (media_ID),
	FOREIGN KEY (uploader) REFERENCES User(user_ID)

);

CREATE TABLE Tag
(
	tag_ID		BIGINT UNSIGNED 		NOT NULL AUTO_INCREMENT,
	description	VARCHAR(255),

	PRIMARY KEY (tag_ID)
);

CREATE TABLE MediaTag
(
	tag_ID		BIGINT UNSIGNED			NOT NULL,
	media_ID	BIGINT UNSIGNED 		NOT NULL,
	placing		INT UNSIGNED			NOT NULL,

	PRIMARY KEY (tag_ID, media_ID),
	FOREIGN KEY (tag_ID) REFERENCES Tag(tag_ID) 		ON DELETE CASCADE,
	FOREIGN KEY (media_ID) REFERENCES Media(media_ID) 	ON DELETE CASCADE
);